### ISSUE TITLE
Modules not loaded

### ISSUE THREAD

**Issue by edwardwilson** [thiennn/trymodular#5]
Hello, I cloned this repository and found that none of the modules are loaded correctly. Can someone tell me if I am missing something which needs to be set up?

**Comment by thiennn** [comment]
Please post detail the error messages or screenshots

**Comment by edwardwilson** [comment]
I've downloaded the repository opened and complied. I've ran the app in IISExpress and the site loads fine:

![image](https://cloud.githubusercontent.com/assets/871802/18124780/9c8ef490-6f6b-11e6-9c41-a3a7dfa746de.png)

However when I click on one of the module links I get a blank page: 

![image](https://cloud.githubusercontent.com/assets/871802/18124873/070936b4-6f6c-11e6-8989-ee6fcb29a566.png)

When I look in the dev tools of my browser it's getting a 404 response:

![image](https://cloud.githubusercontent.com/assets/871802/18124914/25d09434-6f6c-11e6-9e0e-57a3665b2cec.png)

**Comment by thiennn** [comment]
Did you build the whole solution? Because modules are on different projects that are not referenced by the WebHost, they do not be built automatically.

**Comment by cevarief** [comment]
Running this on Mac and i get this error : 
```bash
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Modular.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Modular.WebHost.Startup.LoadInstalledModules() in /Users/cevarief/Development/aspnet/git/trymodular/Modular/src/Modular.WebHost/Startup.cs:line 188
   at Modular.WebHost.Startup.ConfigureServices(IServiceCollection services) in /Users/cevarief/Development/aspnet/git/trymodular/Modular/src/Modular.WebHost/Startup.cs:line 58
   --- End of inner exception stack trace ---
```

I find that Modular.Core.dll is already in bin folder.

**Comment by thiennn** [comment]
The newer version of .net core run don't throw a good exception message. Please try to remove the checking  if (ex.Message == "Assembly with same name is already loaded") as I did here https://github.com/simplcommerce/SimplCommerce/blob/master/src/SimplCommerce.WebHost/Extensions/ServiceCollectionExtensions.cs

**Comment by cevarief** [comment]
Thanks it works now. 

I'm wondering if the route can be changed to _localhost:5000/moduleA/TestA_ instead of _localhost:5000/TestA/_ to avoid routing conflict with core module.

**Comment by thiennn** [comment]
try AttributeRouting

**Comment by cevarief** [comment]
Well, attribute Routing is not my preference, since it needs to add it to every module controller. I've just extended the global default route to make it work, the only problem is i could now access both uri /moduleA/TestA and /TestA/. But that's no problem anyway.

Thank you very much.
